name: Copy File to Root on Push

on: [push]

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy file to root
      run: |
        cp Informe/0_main.pdf Informe.pdf
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Informe.pdf
        git commit -m "Move file to root directory"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
